version: '3.8'

services:
  api:
    command: >
      sh -c "npm run test"
    depends_on: 
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin123
      - DB_NAME=express_db
      - DB_PORT=5432
    
  postgres:
    image: postgres:16-alpine
    container_name: express_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: express_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d express_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 