version: 2.1

orbs:
  node: circleci/node@5.1.0
  docker: circleci/docker@2.4.0
  coveralls: coveralls/coveralls@2.2.5

jobs:
  test:
    docker:
      - image: cimg/node:22.14.0
      - image: cimg/postgres:16.1
        environment:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin123
          POSTGRES_DB: express_db_test
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Wait for PostgreSQL
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run Tests
          command: COVERALLS_REPO_TOKEN=z7ysKO8iQCmUAURd2xrXBWVZ7LEnQnS9T npm run test:coverage
          environment:
            NODE_ENV: test
            DB_HOST: localhost
            DB_USER: admin
            DB_PASSWORD: admin123
            DB_NAME: express_db_test
            DB_PORT: 5432

      - store_test_results:
          path: ./test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

  build:
    docker:
      - image: cimg/node:22.14.0
    
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: npm ci

      - run:
          name: Build Application
          command: npm run build

      - persist_to_workspace:
          root: .
          paths:
            - dist
            - package.json
            - package-lock.json

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test 